export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_COMPANY_ADDRESS = "SET_COMPANY_ADDRESS";
export const SET_CURRENT_USER_ADDRESS = "SET_CURRENT_USER_ADDRESS";
export const SET_PERSONAL_REFERENCE = "SET_PERSONAL_REFERENCES";
export const SET_WORK_REFERENCE = "SET_WORK_REFERENCE";
export const SET_ADDRESS_PROOF = "SET_ADDRESS_PROOF";
export const SET_PERMANENT_USER_ADDRESS = "SET_PERMANENT_USER_ADDRESS";
export const SET_GEOLOCATION_CORDINATES = "SET_GEOLOCATION_CORDINATES";
export const SET_ELIGIBILITY_DATA = "SET_ELIGIBILITY_DATA";
export const SET_KYC_COMPLETED = "SET_KYC_COMPLETED";
export const SET_PLANS_DETAILS = "SET_PLANS_DETAILS";
export const SET_PAN_PROGRESS_CALCULATOR = "SET_PAN_PROGRESS_CALCULATOR";
export const SET_KYC_PROGRESS_CALCULATOR = "SET_KYC_PROGRESS_CALCULATOR";
export const SET_EMOPLOYEMENT_PROGRESS_CALCULATOR =
  "SET_EMPLOYEMENT_PROGRESS_CALCULATOR";
export const SET_PERSONAL_PROGRESS_CALCULATOR =
  "SET_PERSONAL_PROGRESS_CALCULATOR";
export const SET_BANKDETAILS_PROGRESS_CALCULATOR =
  "SET_BANKDETAILS_PROGRESS_CALCULATOR";
export const SET_PROFILE_DETAILS = "SET_PROFILE_DETAILS";
export const SET_USER_LOAN_DETAILS = "SET_USER_LOAN_DETAILS";
export const SET_USER_GEMAIL_ACOUNT_ACCESS = "SET_USER_GEMAIL_ACOUNT_ACCESS";
export const SET_SELECT_BUTTON_STATUS = "SET_SELECT_BUTTON_STATUS";
export const SET_LOAN_ID = "SET_LOAN_ID";
export const SET_WEBVIEW_CLOSE = "SET_WEBVIEW_CLOSE";
